//
//  URLRequest+Extension.swift
//
//
//  Created by Mohamed Khater on 09/10/2024.
//

import Foundation

public extension URLRequest {
    /// Initializes a `URLRequest` with the specified URL and a multipart request.
    ///
    /// This initializer sets the HTTP header and body of the request based on the provided `Multipart` instance.
    ///
    /// - Parameters:
    ///   - url: The URL for the request.
    ///   - multipart: An instance of `Multipart` that contains the data to be sent in the request.
    ///
    /// - Note: The HTTP header is set to `Content-Type: multipart/<disposition>; boundary=<boundary>`,
    /// and the HTTP body is set to the data generated by the multipart request.
    init(url: URL, multipart: Multipart) {
        self.init(url: url)
        addValue(multipart.httpHeader.value, forHTTPHeaderField: multipart.httpHeader.field)
        httpBody = multipart.httpBody
    }
}
